# Backup system configuration
#sched  ule = "0 4 * * *"  # Daily at 4 AM
temp_dir = "" # Will create a new random temp directory if not specified
debug = false

[compression]
format = "zstd"  # or "zstd"
level = 3        # Compression level (1-9)

[mysql]
enabled = false
host = "localhost"
port = "3306"
user = "backup_user"
password = "backup_password"
database = "myapp"

[filesystem]
enabled = true
#base_path = "D:\\projects\\mcpt\\backups\\test"
base_path = "/tmp/backups/"
include_patterns = [
    "*.txt",
    "*.pdf",
    "config/**",
    "data/**"
]
exclude_patterns = [
    ".git/**",
    "node_modules/**",
    "tmp/**",
    "*.tmp"
]

[s3]
endpoint = "https://9ef674c7e3182148b5b136fa79415e76.r2.cloudflarestorage.com/wlmoj-backups"
region = "auto"
bucket = "wlmoj-backups"
access_key_id = "f1867f1a5889ec3e93916bdbd940866e"
secret_access_key = "eeb3b7d7c4b1273822f08cfa8484b583eab2b26ea7c5d3ff697837681898f996"
max_concurrency = 10
part_size=0