# Backup system configuration
#schedule = "0 4 * * *"  # Daily at 4 AM
temp_dir = "" # Will create a new random temp directory if not specified
debug = false

[compression]
format = "zstd"  # or "zlib" or "zstd"
level = 3        # Compression level (1-9)

[mysql]
enabled = false
host = "localhost"
port = "3306"
user = "backup_user"
password = "backup_password"
database = "myapp"

[filesystem]
enabled = true
base_path = "D:\\projects\\mcpt\\backups\\test"
include_patterns = [
    "*.txt",
    "*.pdf",
    "config/**",
    "data/**"
]
exclude_patterns = [
    ".git/**",
    "node_modules/**",
    "tmp/**",
    "*.tmp"
]

[s3]
endpoint = "https://s3.amazonaws.com"
region = "us-east-1"
bucket = "my-backup-bucket"
access_key_id = "your_access_key"
secret_access_key = "your_secret_key"
max_concurrency = 10
part_size=0